import * as yup from 'yup';
import SchemaConstants from './SchemaConstants';
import { BaseEntity } from './BaseEntity';
import { Phases, defaultPhases } from './Phase';
import { defaultChores, Chores } from './Chore';
import { Roles } from './Roles';
import { Dispute } from './Dispute';
import { GenderFilter } from './HouseSearch';
import { Issues } from './Issue';
import { HouseApplications } from './Application';
import { Complaints } from './Complaint';
import { Rooms } from './Room';
import { SubscriptionStatus } from './User';

export type PartialHouseWithId = Partial<House> & { id: string };

export interface AwaitingVerification {
  firstName: string;
  lastName: string;
  userId: string;
}

export interface HouseHealth {
  [weekEndDate: string]: number;
}

export type ManagerSetupType =
  | 'senior-peer'
  | 'operator-only'
  | 'external-managers'
  | 'democratic';

export const HouseActionItems: HouseActionType[] = [
  'issues',
  'applications',
  'disputes',
  'complaints',
];
export type HouseActionType =
  | 'issues'
  | 'applications'
  | 'disputes'
  | 'complaints';

export class House extends BaseEntity {
  // ID generated by houseService.createHouseId() at creation time, not in constructor.
  // Keeping the default empty avoids a Firestore call on every deserialization.
  id: string = '';
  timezone: string = ''; // needed for cloud scheduler function
  ownerId: string = '';
  lat!: number;
  lng!: number;
  geohash: string = '';
  /** @deprecated Use adminIds[] instead. Kept for backward compat with legacy Firestore docs. */
  adminId: string = '';
  adminIds: string[] = [];
  superAdminIds: string[] = [];
  street: string = '';
  city: string = '';
  country: string = '';
  health: HouseHealth = {};
  name: string = '';
  monthlyRent: number = 0;
  weeklyRent: number = 0;
  currentCapacity: number = 0;
  maximumCapacity: number = 1;
  state: string = '';
  zip: string = '';
  code: string = '';
  avatar: string = '';
  imageUrl: string = '';
  depositsAndFees: string | number = 0;
  certified: boolean = false;
  phoneNumber: string = '';
  rentFrequency: 'weekly' | 'monthly' | 'both' = 'both';
  pendingAdminInvites?: string[] = [];
  pendingGuestInvites?: string[] = [];
  // LOAD-BEARING DEFAULT, not a placeholder: the setup wizard builds a house
  // with `new House()` (screens/SetupWizards/OrgSetup.tsx, HouseSetup.tsx) and
  // nothing else on the client writes this field, so this is what stamps a new
  // house's status. The server denies an absent status
  // (functions/src/util/entitlement.ts), so emptying this default would lock
  // out every newly created house. Stamping it server-side at house creation
  // is the real fix; until then, do not "clean this up".
  // (Trial length itself is TRIAL_PERIOD_DAYS in functions/src/api/stripe.ts.)
  subscriptionStatus: SubscriptionStatus = 'trialing';
  guestGraceEndsAt?: string = undefined;
  isDemoHouse: boolean = false;
  // House model type — gates Oxford House features
  houseType: 'traditional' | 'oxford' = 'traditional';
  oxfordOnboardingComplete?: boolean = undefined;
  eesMonthlyAmount?: number = undefined;
  seniorPeerEmails?: string[] = [];
  managerSetupType: ManagerSetupType = 'operator-only';
  awaitingVerification: AwaitingVerification[] = [];
  chores: Chores = defaultChores;
  phases: Phases = defaultPhases;
  gender: GenderFilter = '';
  disputes: {
    [id: string]: Dispute;
  } = {};
  issues: Issues = {};
  applications: HouseApplications = {};
  complaints: Complaints = {};
  rooms: Rooms = {};
  baths: number = 1;
  wifi: boolean = false;
  rating: number = 3;

  // Stripe Connect (resident payments)
  stripeAccountId?: string = undefined;
  stripeStatus: StripeAccountStatus = StripeAccountStatus.NOT_CONNECTED;
  stripeConnectedAt?: number = undefined;
  stripeLastSyncAt?: number = undefined;
  stripeError?: string = undefined;
}

export enum StripeAccountStatus {
  NOT_CONNECTED = 'not_connected',
  PENDING = 'pending',
  ACTIVE = 'active',
  RESTRICTED = 'restricted',
  DISCONNECTED = 'disconnected',
}

export const houseSchema = yup.object().shape({
  gender: yup
    .string()
    .oneOf(['male', 'female', 'non-binary', ''], SchemaConstants.REQUIRED)
    .required(SchemaConstants.REQUIRED),
  maximumCapacity: yup
    .number()
    .required(SchemaConstants.REQUIRED)
    .max(5000, SchemaConstants.numberMax(5000))
    .min(0, SchemaConstants.numberMin(0)),
  monthlyRent: yup
    .number()
    .max(5000, SchemaConstants.numberMax(5000))
    .min(0, SchemaConstants.numberMin(0)),
  weeklyRent: yup
    .number()
    .min(0, SchemaConstants.numberMin(0))
    .max(5000, SchemaConstants.numberMax(5000)),
  phoneNumber: yup
    .string()
    .required(SchemaConstants.REQUIRED)
    .min(10, SchemaConstants.stringMin(10))
    .max(14, SchemaConstants.stringMax(15)),
  id: yup.string().required(),
  name: yup.string().required(SchemaConstants.REQUIRED),
});
