import RNHTMLtoPDF from 'react-native-html-to-pdf';
import {Share, Platform} from 'react-native';
import {format} from 'date-fns';

export interface PhoneListMember {
  displayName: string;
  phoneNumber: string;
  position?: string;
}

/**
 * Service for generating and sharing group phone list reports as PDF.
 * Follows the same pattern as TreasuryReportService.
 */
export class PhoneListReportService {
  /**
   * Generate HTML content for the phone list report.
   */
  static generateReportHTML(
    members: PhoneListMember[],
    groupName: string,
    generatedDate: Date,
  ): string {
    const formatDate = (date: Date) => format(date, 'MMM d, yyyy h:mm a');

    const sorted = [...members].sort((a, b) =>
      a.displayName.localeCompare(b.displayName),
    );

    const memberRows = sorted
      .map(
        member => `
        <tr>
          <td style="padding: 10px 12px;">${member.displayName}</td>
          <td style="padding: 10px 12px;">${member.phoneNumber || '—'}</td>
          <td style="padding: 10px 12px; color: #757575;">${
            member.position || ''
          }</td>
        </tr>
      `,
      )
      .join('');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #212121;
            background-color: #ffffff;
          }
          .header {
            text-align: center;
            margin-bottom: 24px;
            padding-bottom: 16px;
            border-bottom: 2px solid #1976D2;
          }
          .header h1 {
            color: #1976D2;
            margin: 0 0 8px 0;
            font-size: 24px;
          }
          .header .subtitle {
            color: #757575;
            font-size: 14px;
          }
          .section {
            margin-bottom: 24px;
          }
          .section-title {
            font-size: 16px;
            font-weight: bold;
            color: #1976D2;
            margin-bottom: 12px;
            padding-bottom: 4px;
            border-bottom: 1px solid #E0E0E0;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
          }
          thead {
            background: #F5F5F5;
          }
          th {
            padding: 10px 12px;
            text-align: left;
            font-weight: 600;
            color: #424242;
          }
          tbody tr {
            border-bottom: 1px solid #E0E0E0;
          }
          tbody tr:last-child {
            border-bottom: none;
          }
          tbody tr:nth-child(even) {
            background-color: #FAFAFA;
          }
          .footer {
            margin-top: 32px;
            padding-top: 16px;
            border-top: 1px solid #E0E0E0;
            font-size: 12px;
            color: #9E9E9E;
            text-align: center;
          }
          .no-data {
            color: #9E9E9E;
            font-style: italic;
            padding: 16px;
            text-align: center;
          }
          .member-count {
            font-size: 13px;
            color: #757575;
            margin-bottom: 8px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${groupName}</h1>
          <div class="subtitle">Member Phone List</div>
          <div class="subtitle">Generated: ${formatDate(generatedDate)}</div>
        </div>

        <div class="section">
          <div class="section-title">Members (${members.length})</div>
          ${
            memberRows
              ? `
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Position</th>
              </tr>
            </thead>
            <tbody>
              ${memberRows}
            </tbody>
          </table>
          `
              : '<div class="no-data">No members with phone numbers</div>'
          }
        </div>

        <div class="footer">
          <p><strong>Confidential — Group Members Only</strong></p>
          <p>This phone list is for recovery support purposes only.
          Please do not distribute outside the group.</p>
          <p>Generated by Homegroups on ${formatDate(generatedDate)}</p>
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Generate a PDF file from the phone list.
   */
  static async generatePDF(
    members: PhoneListMember[],
    groupName: string,
  ): Promise<string> {
    try {
      const html = PhoneListReportService.generateReportHTML(
        members,
        groupName,
        new Date(),
      );

      const fileName = `${groupName.replace(
        /[^a-zA-Z0-9]/g,
        '_',
      )}_Phone_List_${format(new Date(), 'yyyy-MM-dd')}`;

      const options = {
        html,
        fileName,
        directory: Platform.OS === 'ios' ? 'Documents' : 'Download',
      };

      const file = await RNHTMLtoPDF.convert(options);

      if (!file.filePath) {
        throw new Error('Failed to generate PDF');
      }

      return file.filePath;
    } catch (error) {
      console.error('Error generating phone list PDF:', error);
      throw error;
    }
  }

  /**
   * Generate PDF and share via the native share sheet.
   */
  static async generateAndShare(
    members: PhoneListMember[],
    groupName: string,
  ): Promise<void> {
    try {
      const filePath = await PhoneListReportService.generatePDF(
        members,
        groupName,
      );

      await Share.share({
        url: Platform.OS === 'ios' ? filePath : `file://${filePath}`,
        title: `${groupName} Phone List`,
      });
    } catch (error) {
      console.error('Error sharing phone list PDF:', error);
      throw error;
    }
  }
}
