import { FirebaseFirestoreTypes } from '@react-native-firebase/firestore';
import { BaseEntity } from '../entities/BaseEntity';

type DocumentReference<T extends DocumentData = DocumentData> =
  FirebaseFirestoreTypes.DocumentReference<T>;
type DocumentData = FirebaseFirestoreTypes.DocumentData;
type CollectionReference<T extends DocumentData = DocumentData> =
  FirebaseFirestoreTypes.CollectionReference<T>;

// Base interface for entities that can be stored in Firestore
// More flexible than BaseEntity class for entities with custom timestamp handling
interface FirestoreEntity {
  id?: string;
  uid?: string;
}

function checkId<T extends FirestoreEntity>(object: T) {
  if (!object.uid && !object.id) {
    throw new Error('Item must have an id or uid attribute');
  }
}

function createId(collection: CollectionReference) {
  return collection.doc().id;
}

/**
 * Gets an item from a collection by id
 * @param collection
 * @param id
 */
async function get<T extends FirestoreEntity>(
  collection: CollectionReference,
  id: string,
): Promise<T> {
  const snapshot = await collection.doc(id).get();
  return snapshot.data() as T;
}

/**
 * Gets items from a collection where attribute === value
 * If no items in the collection meet the criteria, this method will
 * return an empty array
 * @param collection
 * @param attribute
 * @param operator
 * @param value
 */
async function getByAttribute<T extends FirestoreEntity>(
  collection: CollectionReference,
  attribute: string,
  operator: FirebaseFirestore.WhereFilterOp,
  value: string | number | boolean | null,
): Promise<T[]> {
  const result = await collection.where(attribute, operator, value).get();
  return result.docs.length ? result.docs.map(doc => doc.data() as T) : [];
}

/**
 * Updates an item in the given collection
 * @param collection
 * @param object
 */
async function update<T extends FirestoreEntity>(
  collection: CollectionReference,
  object: Partial<T>,
): Promise<void> {
  // firebase users have uids instead of ids
  checkId(object as FirestoreEntity);
  return collection.doc(object.uid ? object.uid : object.id).update(object);
}

async function deleteObject<T extends FirestoreEntity>(
  collection: CollectionReference,
  object: T,
) {
  checkId(object);
  // firebase users have uids instead of ids
  return collection.doc(object.uid ? object.uid : object.id!).delete();
}

/**
 * Creates a document in the given firestore collection. If given an id, it will create the document with that id,
 * otherwise one will be generated by firestore.
 * @param collection
 * @param object
 * @param id
 */
async function create<T extends FirestoreEntity>(
  collection: CollectionReference,
  object: T,
  id?: string,
): Promise<T> {
  if (!object.id) {
    object.id = id || collection.doc().id;
  }
  await collection.doc(object.id).set(object as unknown as DocumentData);
  return object;
}

async function add<T extends FirestoreEntity>(
  collection: CollectionReference,
  object: T,
): Promise<DocumentReference<DocumentData>> {
  return collection.add(object as unknown as DocumentData);
}

export { get, getByAttribute, update, deleteObject, create, add, createId };
