/**
 * Receipt Service
 *
 * Generates shareable payment receipt text for rent and manual payments.
 * Uses React Native Share API rather than PDF to avoid html-to-pdf
 * build issues on iOS.
 */
import { Share, Platform } from 'react-native';
import { logException } from '../util/logging';

export interface ReceiptData {
  paymentId: string;
  guestName: string;
  houseName: string;
  amountInCents: number;
  method: string; // 'Card', 'Cash', 'Check', 'Venmo', 'Zelle'
  date: string; // ISO date string
  description?: string;
  status: 'succeeded' | 'pending' | 'failed' | 'resolved_offline';
}

function formatCurrency(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

/**
 * Generate a plain-text receipt suitable for sharing via SMS, email, etc.
 */
export function generateReceiptText(receipt: ReceiptData): string {
  const lines = [
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '       PAYMENT RECEIPT',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    `Date:      ${formatDate(receipt.date)}`,
    `Resident:  ${receipt.guestName}`,
    `House:     ${receipt.houseName}`,
    '',
    `Amount:    ${formatCurrency(receipt.amountInCents)}`,
    `Method:    ${receipt.method}`,
    `Status:    ${receipt.status === 'succeeded' ? 'Paid' : receipt.status}`,
    receipt.description ? `For:       ${receipt.description}` : '',
    '',
    `Receipt #: ${receipt.paymentId.slice(0, 12).toUpperCase()}`,
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    'Generated by Regroup',
  ].filter(Boolean);

  return lines.join('\n');
}

/**
 * Share a payment receipt via the native share sheet.
 */
export async function shareReceipt(receipt: ReceiptData): Promise<void> {
  const text = generateReceiptText(receipt);
  const subject = `Payment Receipt - ${receipt.guestName} - ${formatDate(
    receipt.date,
  )}`;

  try {
    await Share.share(
      {
        message: text,
        ...(Platform.OS === 'ios' ? { subject } : {}),
      },
      {
        subject,
        dialogTitle: 'Share Payment Receipt',
      },
    );
  } catch (error) {
    logException(error);
    throw new Error('Failed to share receipt');
  }
}
