import { Platform } from 'react-native';
import { format, parseISO } from 'date-fns';

import { RentPayment } from './payments';

import { Guest } from '../entities/Guest';
import { WeekStats } from '../entities/WeekSummary';
import { PhaseRule } from '../entities/Phase';

// react-native-html-to-pdf is excluded from the iOS autolinked pod set
// (see react-native.config.js) to unblock E2E builds. Load the JS module
// lazily so opening this service on iOS doesn't throw on import.
// Callers should also check isPDFExportAvailable() before invoking.
export function isPDFExportAvailable(): boolean {
  return Platform.OS !== 'ios';
}

/**
 * Generates a PDF compliance report for a guest's week and returns the file path.
 */
export async function exportWeeklyReportPDF(
  guest: Guest,
  stats: WeekStats,
  weekStart: string,
  phaseRules: PhaseRule,
): Promise<string> {
  const html = `
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #2c7be5; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
        th { background: #f0f0f0; }
        .pass { color: green; }
        .fail { color: red; }
      </style>
    </head>
    <body>
      <h1>Weekly Compliance Report</h1>
      <p><strong>Resident:</strong> ${guest.firstName} ${guest.lastName}</p>
      <p><strong>Week of:</strong> ${format(parseISO(weekStart), 'MMMM d, yyyy')}</p>
      <p><strong>Phase:</strong> ${guest.phase}</p>
      <table>
        <tr><th>Activity</th><th>Required</th><th>Completed</th><th>Status</th></tr>
        <tr>
          <td>Meetings</td>
          <td>${phaseRules.meetings ?? 0}</td>
          <td>${stats.meetingsAttended}</td>
          <td class="${stats.meetingsAttended >= (phaseRules.meetings ?? 0) ? 'pass' : 'fail'}">
            ${stats.meetingsAttended >= (phaseRules.meetings ?? 0) ? 'PASS' : 'FAIL'}
          </td>
        </tr>
        <tr>
          <td>Chores</td>
          <td>${phaseRules.chore ? 1 : 0}</td>
          <td>${stats.choresCompleted}</td>
          <td class="${stats.choresCompleted >= (phaseRules.chore ? 1 : 0) ? 'pass' : 'fail'}">
            ${stats.choresCompleted >= (phaseRules.chore ? 1 : 0) ? 'PASS' : 'FAIL'}
          </td>
        </tr>
        <tr>
          <td>Work Hours</td>
          <td>${phaseRules.work ?? 0}</td>
          <td>${stats.hoursWorked}</td>
          <td class="${stats.hoursWorked >= (phaseRules.work ?? 0) ? 'pass' : 'fail'}">
            ${stats.hoursWorked >= (phaseRules.work ?? 0) ? 'PASS' : 'FAIL'}
          </td>
        </tr>
        <tr>
          <td>Medication</td>
          <td>${phaseRules.medications ? 'Required' : 'N/A'}</td>
          <td>${stats.medicationTaken > 0 ? 'Yes' : 'No'}</td>
          <td class="${!phaseRules.medications || stats.medicationTaken > 0 ? 'pass' : 'fail'}">
            ${!phaseRules.medications || stats.medicationTaken > 0 ? 'PASS' : 'FAIL'}
          </td>
        </tr>
        <tr>
          <td>Sponsor Meeting</td>
          <td>${phaseRules.supporter ? 'Required' : 'N/A'}</td>
          <td>${stats.primarySupporterMet > 0 ? 'Yes' : 'No'}</td>
          <td class="${!phaseRules.supporter || stats.primarySupporterMet > 0 ? 'pass' : 'fail'}">
            ${!phaseRules.supporter || stats.primarySupporterMet > 0 ? 'PASS' : 'FAIL'}
          </td>
        </tr>
      </table>
      <p style="margin-top: 30px; font-size: 12px; color: #999;">
        Generated by Regroup — ${format(new Date(), 'MMMM d, yyyy h:mm a')}
      </p>
    </body>
    </html>
  `;

  const options = {
    html,
    fileName: `compliance_${guest.id}_${weekStart}`,
    directory: 'Documents',
  };

  if (!isPDFExportAvailable()) {
    throw new Error(
      'PDF export is temporarily unavailable on iOS. Please try again from the web or Android app.',
    );
  }

  // Lazy require so the JS module isn't loaded (and its native bridge
  // isn't resolved) on platforms where the pod is excluded.
  //
  // `.convert` on the default export, not the named `generatePDF` of the 1.x
  // line: 1.x is a Kotlin rewrite against BaseReactPackage, an API that does
  // not exist in React Native 0.72, so it cannot compile here. 0.12.x is the
  // last all-Java release and takes the same { html, fileName, directory }.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const RNHTMLtoPDF = require('react-native-html-to-pdf').default;
  const file = await RNHTMLtoPDF.convert(options);
  return file.filePath;
}

// ─── CSV Export ───────────────────────────────────────────────────────────────

function escapeCsvField(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

/**
 * Generates a CSV string for a payment history export.
 * guestNames maps guestId → display name for the name column.
 */
export function exportPaymentHistoryCSV(
  payments: RentPayment[],
  guestNames: Record<string, string>,
): string {
  const header = ['Date', 'Guest', 'Amount ($)', 'Status', 'Description'].join(',');
  const rows = payments.map((p) => {
    const date = p.createdAt ? format(parseISO(p.createdAt as string), 'yyyy-MM-dd') : '';
    const guest = escapeCsvField(guestNames[p.guestId] ?? p.guestId);
    const amount = String(p.amount ?? '');
    const status = escapeCsvField(p.status);
    const description = escapeCsvField(p.description ?? '');
    return [date, guest, amount, status, description].join(',');
  });
  return [header, ...rows].join('\n');
}

export interface EESRecord {
  id: string;
  guestId: string;
  type: string;
  amount: number;
  date: string;
  notes?: string;
}

/**
 * Generates a CSV string for an EES (Emergency Expense Sharing) export.
 */
export function exportEESHistoryCSV(
  records: EESRecord[],
  guestNames: Record<string, string>,
): string {
  const header = ['Date', 'Guest', 'Type', 'Amount ($)', 'Notes'].join(',');
  const rows = records.map((r) => {
    const date = r.date ? format(parseISO(r.date), 'yyyy-MM-dd') : '';
    const guest = escapeCsvField(guestNames[r.guestId] ?? r.guestId);
    const type = escapeCsvField(r.type);
    const amount = String(r.amount ?? '');
    const notes = escapeCsvField(r.notes ?? '');
    return [date, guest, type, amount, notes].join(',');
  });
  return [header, ...rows].join('\n');
}
