import { Share, Platform } from 'react-native';
import { FinancialRecord } from '../entities/oxford/FinancialRecord';
import { logException } from '../util/logging';

function fmt(cents: number): string {
  const abs = Math.abs(cents);
  const sign = cents < 0 ? '-' : '';
  return `${sign}$${(abs / 100)
    .toFixed(2)
    .replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function periodRange(weekStart: string): string {
  const mon = new Date(weekStart);
  const sun = new Date(mon);
  sun.setDate(mon.getDate() + 6);
  return `${fmtDate(mon.toISOString())} — ${fmtDate(sun.toISOString())}`;
}

export function generateWeeklyReport(
  record: FinancialRecord,
  houseName: string,
  submitterName: string,
  approverName?: string,
): string {
  const lines: string[] = [
    '═══════════════════════════════════════════════',
    '  WEEKLY OXFORD HOUSE FINANCIAL STATUS REPORT',
    '═══════════════════════════════════════════════',
    '',
    `House:    ${houseName}`,
    `Period:   ${periodRange(record.period)}`,
    `Status:   ${
      record.status.charAt(0).toUpperCase() + record.status.slice(1)
    }`,
    '',
    '─── BALANCES ──────────────────────────────────',
    `Checking (beginning of week)    ${fmt(record.beginningCheckingBalance)}`,
  ];

  if (record.savingsBalance != null) {
    lines.push(`Savings                         ${fmt(record.savingsBalance)}`);
  }

  lines.push('', '─── CASH & RECEIPTS FROM MEMBERS ──────────────');
  for (const line of record.incomeLines) {
    const desc = line.description ? ` (${line.description})` : '';
    lines.push(`${line.category}${desc}`.padEnd(36) + fmt(line.amount));
  }
  lines.push(''.padEnd(36) + '──────────');
  lines.push('Total Receipts'.padEnd(36) + fmt(record.totalIncome));

  lines.push('', '─── AMOUNT PAID OUT ───────────────────────────');
  for (const line of record.expenseLines) {
    const payee = line.payee ? `  ${line.payee}` : '';
    const check = line.checkNumber ? `  #${line.checkNumber}` : '';
    lines.push(
      `${line.category}${payee}${check}`.padEnd(36) + fmt(line.amount),
    );
  }
  lines.push(''.padEnd(36) + '──────────');
  lines.push('Total Paid Out'.padEnd(36) + fmt(record.totalExpenses));

  lines.push('', '─── ENDING BALANCE ────────────────────────────');
  lines.push(
    'Checking (end of week)'.padEnd(36) + fmt(record.endingCheckingBalance),
  );

  if (record.billsDue.length > 0) {
    lines.push('', '─── BILLS TO BE PAID (next 30 days) ───────────');
    for (const bill of record.billsDue) {
      lines.push(
        `${bill.description}`.padEnd(20) +
          `Due ${fmtDate(bill.dueDate)}`.padEnd(16) +
          fmt(bill.amount),
      );
    }
  }

  lines.push('');
  lines.push(
    `Submitted by: ${submitterName} on ${
      record.submittedAt ? fmtDate(record.submittedAt) : 'unknown'
    }`,
  );
  if (approverName && record.approvedAt) {
    lines.push(
      `Approved by:  ${approverName} on ${fmtDate(record.approvedAt)}`,
    );
  }
  lines.push('', '═══════════════════════════════════════════════');
  lines.push('Generated by Regroup (RATS)');

  return lines.join('\n');
}

export async function shareWeeklyReport(
  record: FinancialRecord,
  houseName: string,
  submitterName: string,
  approverName?: string,
): Promise<void> {
  const text = generateWeeklyReport(
    record,
    houseName,
    submitterName,
    approverName,
  );
  const subject = `Oxford House Financial Report — ${periodRange(
    record.period,
  )}`;
  try {
    await Share.share(
      { message: text, ...(Platform.OS === 'ios' ? { subject } : {}) },
      { subject, dialogTitle: 'Share Financial Report' },
    );
  } catch (error) {
    logException(error);
    throw new Error('Failed to share report');
  }
}
