import { House, StripeAccountStatus } from '../House';
import { DEFAULT_PHASE } from '../Phase';

describe('House entity', () => {
  describe('constructor with no args', () => {
    it('does not throw when instantiated', () => {
      expect(() => new House()).not.toThrow();
    });

    it('defaults id to empty string (ID generated by service layer)', () => {
      const house = new House();
      expect(house.id).toBe('');
    });
  });

  describe('default field values — strings', () => {
    let house: House;

    beforeEach(() => {
      house = new House();
    });

    it('defaults timezone to empty string', () => {
      expect(house.timezone).toBe('');
    });

    it('defaults ownerId to empty string', () => {
      expect(house.ownerId).toBe('');
    });

    it('defaults adminId to empty string', () => {
      expect(house.adminId).toBe('');
    });

    it('defaults street to empty string', () => {
      expect(house.street).toBe('');
    });

    it('defaults city to empty string', () => {
      expect(house.city).toBe('');
    });

    it('defaults country to empty string', () => {
      expect(house.country).toBe('');
    });

    it('defaults name to empty string', () => {
      expect(house.name).toBe('');
    });

    it('defaults state to empty string', () => {
      expect(house.state).toBe('');
    });

    it('defaults zip to empty string', () => {
      expect(house.zip).toBe('');
    });

    it('defaults code to empty string', () => {
      expect(house.code).toBe('');
    });

    it('defaults avatar to empty string', () => {
      expect(house.avatar).toBe('');
    });

    it('defaults imageUrl to empty string', () => {
      expect(house.imageUrl).toBe('');
    });

    it('defaults phoneNumber to empty string', () => {
      expect(house.phoneNumber).toBe('');
    });

    it('defaults geohash to empty string', () => {
      expect(house.geohash).toBe('');
    });

    it('defaults subscriptionStatus to "trialing"', () => {
      expect(house.subscriptionStatus).toBe('trialing');
    });
  });

  describe('default field values — numbers', () => {
    let house: House;

    beforeEach(() => {
      house = new House();
    });

    it('defaults monthlyRent to 0', () => {
      expect(house.monthlyRent).toBe(0);
    });

    it('defaults weeklyRent to 0', () => {
      expect(house.weeklyRent).toBe(0);
    });

    it('defaults currentCapacity to 0', () => {
      expect(house.currentCapacity).toBe(0);
    });

    it('defaults maximumCapacity to 1', () => {
      expect(house.maximumCapacity).toBe(1);
    });

    it('defaults depositsAndFees to 0', () => {
      expect(house.depositsAndFees).toBe(0);
    });

    it('defaults baths to 1', () => {
      expect(house.baths).toBe(1);
    });

    it('defaults rating to 3', () => {
      expect(house.rating).toBe(3);
    });
  });

  describe('default field values — booleans', () => {
    let house: House;

    beforeEach(() => {
      house = new House();
    });

    it('defaults certified to false', () => {
      expect(house.certified).toBe(false);
    });

    it('defaults isDemoHouse to false', () => {
      expect(house.isDemoHouse).toBe(false);
    });

    it('defaults wifi to false', () => {
      expect(house.wifi).toBe(false);
    });
  });

  describe('default field values — arrays and objects', () => {
    let house: House;

    beforeEach(() => {
      house = new House();
    });

    it('defaults adminIds to an empty array', () => {
      expect(house.adminIds).toEqual([]);
    });

    it('defaults superAdminIds to an empty array', () => {
      expect(house.superAdminIds).toEqual([]);
    });

    it('defaults awaitingVerification to an empty array', () => {
      expect(house.awaitingVerification).toEqual([]);
    });

    it('defaults pendingAdminInvites to an empty array', () => {
      expect(house.pendingAdminInvites).toEqual([]);
    });

    it('defaults pendingGuestInvites to an empty array', () => {
      expect(house.pendingGuestInvites).toEqual([]);
    });

    it('defaults health to an empty object', () => {
      expect(house.health).toEqual({});
    });

    it('defaults disputes to an empty object', () => {
      expect(house.disputes).toEqual({});
    });

    it('defaults issues to an empty object', () => {
      expect(house.issues).toEqual({});
    });

    it('defaults applications to an empty object', () => {
      expect(house.applications).toEqual({});
    });

    it('defaults complaints to an empty object', () => {
      expect(house.complaints).toEqual({});
    });

    it('defaults rooms to an empty object', () => {
      expect(house.rooms).toEqual({});
    });
  });

  describe('default field values — union types', () => {
    let house: House;

    beforeEach(() => {
      house = new House();
    });

    it('defaults rentFrequency to "both"', () => {
      expect(house.rentFrequency).toBe('both');
    });

    it('defaults houseType to "traditional"', () => {
      expect(house.houseType).toBe('traditional');
    });

    it('defaults managerSetupType to "operator-only"', () => {
      expect(house.managerSetupType).toBe('operator-only');
    });

    it('defaults gender to empty string', () => {
      expect(house.gender).toBe('');
    });
  });

  describe('Stripe fields', () => {
    let house: House;

    beforeEach(() => {
      house = new House();
    });

    it('defaults stripeStatus to NOT_CONNECTED', () => {
      expect(house.stripeStatus).toBe(StripeAccountStatus.NOT_CONNECTED);
    });

    it('defaults stripeAccountId to undefined', () => {
      expect(house.stripeAccountId).toBeUndefined();
    });

    it('defaults stripeConnectedAt to undefined', () => {
      expect(house.stripeConnectedAt).toBeUndefined();
    });

    it('defaults stripeLastSyncAt to undefined', () => {
      expect(house.stripeLastSyncAt).toBeUndefined();
    });

    it('defaults stripeError to undefined', () => {
      expect(house.stripeError).toBeUndefined();
    });
  });

  describe('phases and chores', () => {
    it('initialises phases with the Default phase', () => {
      const house = new House();
      expect(house.phases).toHaveProperty(DEFAULT_PHASE);
    });

    it('initialises chores with Bathroom, Living Room, and Kitchen', () => {
      const house = new House();
      expect(house.chores).toHaveProperty('Bathroom');
      expect(house.chores).toHaveProperty('Living Room');
      expect(house.chores).toHaveProperty('Kitchen');
    });
  });

  describe('field mutation', () => {
    it('allows name to be set after construction', () => {
      const house = new House();
      house.name = 'Sunrise House';
      expect(house.name).toBe('Sunrise House');
    });

    it('allows monthlyRent to be updated', () => {
      const house = new House();
      house.monthlyRent = 750;
      expect(house.monthlyRent).toBe(750);
    });
  });
});

describe('StripeAccountStatus enum', () => {
  it('has the expected values', () => {
    expect(StripeAccountStatus.NOT_CONNECTED).toBe('not_connected');
    expect(StripeAccountStatus.PENDING).toBe('pending');
    expect(StripeAccountStatus.ACTIVE).toBe('active');
    expect(StripeAccountStatus.RESTRICTED).toBe('restricted');
    expect(StripeAccountStatus.DISCONNECTED).toBe('disconnected');
  });
});
