/**
 * Overview screen keys become the NavBar titles
 * e.g. houseMedications has a NavBar title of House Medications
 */

import { Stat } from '../entities/Guest';
import { Routes } from '../navigation/types';

const tab = (name: string) => `tab-${name}`;
export const tabs = {
  house: tab('house'),
  guest: tab('guest'),
  activities: tab('activities'),
  contacts: tab('contacts'),
  houseChat: tab('houseChat'),
  personal: tab('personal'),
};

const routes = {
  setup: 'setup',
  issues: 'issues',
  complaints: 'complaints',
  guestInfo: 'guestInfo',
  beds: 'beds',
  applications: 'applications',
  houseConfig: 'houseConfig',
  newMeeting: 'newMeeting',
  meetingSearch: 'meetingSearch',
  choreSetup: 'choreSetup',
  operatorSetupWizard: 'operatorSetupWizard',
  choreDetailSetup: 'choreDetailSetup',
  phaseCustomization: 'phaseCustomization',
  managerSetup: 'managerSetup',
  phaseSetup: 'phaseSetup',
  userSettings: 'userSettings',
  setupWizard: 'setupWizard',
  houseSettings: 'houseSettings',
  stripeSettings: 'stripeSettings',
  houseSetup: 'houseSetup',
  subscriptionHandler: 'subscriptionHandler',
  initialLanding: 'initialLanding',
  managerIntro: 'managerIntro',
  houseSearch: 'houseSearch',
  inAppSetupWizard: 'inAppSetupWizard',
  orgSetup: 'orgSetup',
  guestInvite: 'guestInvite',
  editUserInfo: 'editUserInfo',
  introHouseSummary: 'introHouseSummary',
  introduction: 'introduction',
  housesOverview: 'housesOverview',
  managerDashboard: 'managerDashboard',
  notifications: 'notifications',
  signup: 'signup',
  login: 'login',
  landing: 'landing',
  newAccount: 'newAccount',
  houseCode: 'houseCode',
  houseChat: 'houseChat',
  houseList: 'houseList',
  houseDisputes: 'houseDisputes',
  houseSummary: 'houseSummary',
  guestSummary: 'guestSummary',
  guestDetails: 'guestDetails',
  guestLog: 'guestLog',
  createGuest: 'createGuest',
  activities: 'activities',
  guestList: 'guestList',
  directMessage: 'directMessage',
  guestOverview: 'guestOverview',
  choreOverview: 'residentChores',
  choreSummary: 'choreSummary',
  choreActivity: 'choreActivity',
  choreInfo: 'choreInfo',
  workOverview: 'residentWork',
  workSummary: 'workSummary',
  workActivity: 'workActivity',
  workInfo: 'workInfo',
  supporterOverview: 'supporterOverview',
  supporterSummary: 'supporterSummary',
  supporterActivity: 'supporterActivity',
  supporterInfo: 'supporterInfo',
  meetingOverview: 'residentMeetings',
  meetingSummary: 'meetingSummary',
  meetingActivity: 'meetingActivity',
  meetingInfo: 'meetingInfo',
  medicationOverview: 'residentMedications',
  medicationSummary: 'medicationSummary',
  medicationActivity: 'medicationActivity',
  medicationInfo: 'medicationInfo',
  houseDetails: 'houseDetails',
  houseOverview: 'houseOverview',
  houseActivity: 'houseActivity',
  houseInfo: 'houseInfo',
  sendInvites: 'sendInvites',
  guestUpdate: 'guestUpdate',
  personal: 'personal',
  contacts: 'contacts',
  main: 'main',
  priorAuth: 'priorAuth',
};

export const STAT_ROUTE: Record<Stat, string> = {
  hoursWorked: Routes.WorkSummary,
  choreCompleted: Routes.ChoreSummary,
  meeting: Routes.MeetingSummary,
  medication: Routes.MedicationSummary,
  metPrimarySupporter: Routes.SupporterSummary,
};

export default routes;
