default_platform(:ios)

platform :ios do
  desc "Upload metadata and screenshots to App Store Connect"
  lane :metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: false,
      screenshots_path: "./fastlane/screenshots/ios",
      metadata_path: "./fastlane/metadata",
      submit_for_review: false,
      force: true,
      privacy_url: "https://regroup-app.com/privacy-policy",
      overwrite_screenshots: true
    )
  end

  desc "Capture screenshots using Detox"
  lane :screenshots do
    sh("cd .. && npm run test:e2e:build:ios 2>&1")
    sh("cd .. && npx detox test e2e/screenshots.e2e.ts --configuration ios.sim.debug --artifacts-location ./fastlane/screenshots/ios 2>&1")
  end
end

platform :android do
  desc "Upload metadata and screenshots to Play Store (internal track)"
  lane :metadata do
    supply(
      track: "internal",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_screenshots: false,
      screenshots_path: "./fastlane/screenshots/android",
      metadata_path: "./fastlane/metadata/android",
    )
  end

  desc "Capture screenshots using Detox on Android"
  lane :screenshots do
    sh("cd .. && npx detox test e2e/screenshots.e2e.ts --configuration android.emu.debug --artifacts-location ./fastlane/screenshots/android 2>&1")
  end
end
