# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

$RNFirebaseAsStaticFramework = true
platform :ios, '16.0'
prepare_react_native_project!

# ⬇️ uncomment the permissions you need
setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  # 'Camera',
  # 'Contacts',
  # 'FaceID',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  # 'Notifications',
  # 'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
end

target 'RecoveryConnect' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  config = use_native_modules!
  use_frameworks! :linkage => :static

  pod 'SexyTooltip',:git => 'https://github.com/prscX/SexyTooltip.git'

  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  pod 'Stripe', '~> 24.12.0'
  pod 'StripePaymentSheet', '~> 24.12.0'

  # Firebase 11.x for Xcode 16 compatibility (requires @react-native-firebase v21+)
  $FirebaseSDKVersion = '11.6.0'
  
  # Google Maps SDK
  # pod 'GoogleMaps'
  # pod 'GooglePlaces'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Note: Flipper is disabled because it's not compatible with use_frameworks!
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RecoveryConnectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        
        # Fix for .xcprivacy file on device builds
        if target.name == 'FirebaseMessaging'
          config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] ||= ['$(inherited)']
          config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] << '**/PrivacyInfo.xcprivacy'
        end

        # Fix for ARCHS unbound variable
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
      end
    end

    installer.pods_project.targets.each do |target|
      if target.name == 'BoringSSL-GRPC'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            flags = file.settings['COMPILER_FLAGS'].split
            flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
            file.settings['COMPILER_FLAGS'] = flags.join(' ')
          end
        end
      end
    end

    # Fix for BoringSSL-GRPC build issue
    installer.pods_project.targets.each do |target|
      if target.name == 'BoringSSL-GRPC'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-shorten-64-to-32'
        end
      end
    end

    # Fix for fmt library C++ compilation issue
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -DFMT_USE_CHAR8_T=0'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end

    # Fix for gRPC-Core/gRPC-C++ template syntax issue with Xcode 16+
    installer.pods_project.targets.each do |target|
      if ['gRPC-Core', 'gRPC-C++'].include?(target.name)
        target.build_configurations.each do |config|
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -Wno-comma -Wno-unreachable-code -Wno-missing-template-arg-list-after-template-kw'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end

    # Fix for abseil linker issues with Xcode 16
    installer.pods_project.targets.each do |target|
      if target.name == 'abseil'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -ObjC'
        end
      end
    end
  end
end
